### ISSUE TITLE
First complete version of website

### ISSUE THREAD

**Issue by zonca** [galsci/galsci.github.io#1]
@brandonshensley @seclark I've done a first complete draft of the website:

https://galsci.github.io/

We can use the "Blog" section to keep track and put links for the journal club, but even better if we had someone add some notes about the meeting that are then publicly available.

In the readme I have added documentation on how to modify different parts of the website:

https://github.com/galsci/galsci.github.io#readme

For example we need a better homepage image! Also, please improve the description of the group in homepage. You can edit directly on `master`, if anything breaks please open an issue and I can fix it.

**Comment by seclark** [comment]
@zonca this is wonderful, thank you! It is on my list to write more copy -- probably won't get to it this week but will do as soon as I can. This is an excellent starting point. Much appreciated!
